# Generated by Django 3.2 on 2021-06-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
