# Generated by Django 3.2 on 2021-06-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
